### ISSUE TITLE
Adjusting the Spine colors

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#353]
## Global

* [x] In general, change gray from `#5e6a71` to `#717171`

## White

* [x] Spine action items - default `#717171`, hover `#981e32`
* [x] Offside links to `#717171`, hover `#981e32`, always show the offsite icon
* [x] Mobile menu button `#717171`
* [x] List item `border-color: rgba(0,0,0,.1);`

## Dark

* [x] Spine background to `#3b4042`
* [x] Spine action items - default `#d7dadb`, hover `#fff`
* [x] Offsite links to `#d7dadb`, hover `#fff`, always show the offsite icon
* [x] Mobile menu button `#d7dadb`
* [x] List item `border-color: rgba(255,255,255,0.1);`

## Darker

* [x] Spine action items - default `#d7dadb`, hover `#fff`
* [x] Offsite links to `#d7dadb`, hover `#fff`, always show the offsite icon
* [x] Mobile menu button `#d7dadb`
* [x] List item `border-color: rgba(255,255,255,0.1);`

## Crimson

* [x] Spine action items - default `#d7dadb`, hover `#fff`
* [x] Offsite links to `#d7dadb`, hover `#fff`, always show the offsite icon
* [x] Mobile menu button `#d7dadb`
* [x] List item `border-color: #81192a`

**Comment by jeremyBass** [comment]
I will throw this out here again; I think would be helpful for there to be a json object that apps can pull in with the mapping of all brand colors, so that changes like this can propagate when used in the content generated areas out side of the spine.  Up side is that you can use it in the build process as well as out side sources can consume it as needed.  

On example is that I have a few systems that does a build of css and uses the brand colors based on the spine in html elements that I can't adjust the classes.  So I have a custom map of the brand colors that I maintain.  I could pull in this json file from the repo and remap color every so offend when the use choses which version to use.

I know we have talked about this a while back since it is a simple thing.  Just want to put that thought out again given this change came up and request to change the built to use a mapping from a json which should be fairly simple and provide something for other systems to consume easily.  Thank you -Jeremy

**Comment by jeremyfelt** [comment]
The colors above are more for slight adjustments to the Spine itself for contrast reasons. They aren't necessarily all brand colors, so I'm not sure if it is as helpful as the colors listed on https://brand.wsu.edu/visual/colors/. We can probably discuss providing some set of color data via JSON in another issue. It would be interesting to see what kind of demand there was.

**Comment by jeremyBass** [comment]
As far as I recall the brand site had the colors from here too, but didn't double check.  I know Nate said it would.  But the point is that I have a few systems that hold a mapping of the spine colors, so keeping it up to date when minor changes happen is preferred.  I image there are a few others that do or would if they know they could.  Honestly I think it would be hard to tell the demand till it is made but I know there is at least the stores at this vary moment that would benefit for the minor change. Field of dreams type thing here I am betting :D

**Comment by jeremyfelt** [comment]
In [45d785f], I adjusted `$gray-dark` to be `#3b4042` rather than just changing the Spine background for the dark theme.

[ ] Need to verify that this is the right change.

**Comment by jeremyfelt** [comment]
Fixed in #381.
